version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64 #apple silicon: ensure rosetta 2 is installed (if not, 'softwareupdate --install-rosetta')
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
