version: '3.9'

services:
  db:
    container_name: postgresql
    image: postgres
    shm_size: 128mb # set shared memory limit
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
