name: Combine into a .sql.gz file

on:
  push:
    paths:
      - 'sql/*'

jobs:
  combine_sql:
    runs-on: macOS-latest
    name: Combine into a .sql.gz file
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Combine database initialization scripts
      run: 'cat sql/CREATE_TABLES.sql sql/INSERT_INIT_DATA.sql | gzip > init.sql.gz'
    
    - name: Commit the .sql.gz file
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actor
        message: 'Automated .sql.gz file update'
        add: "init.sql.gz"
