name: Render PlantUML files

on:
  pull_request:
    paths:
      - 'docs/uml_diagrams/*.puml'

jobs:
  render_plantuml:
    runs-on: ubuntu-latest
    name: Render .puml files
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: .
        message: "Automated .puml file rendering"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
